version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]
      interval: 1s
      timeout: 20s
      retries: 20
      start_period: 1s
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nw

  redis:
    container_name: redis
    image: redis:7.0.7
    ports:
      - "6379:6379"
    networks:
      - nw

  nifty:
    profiles:
      - all
    container_name: nifty
    image: acartine/nifty:v1
    ports:
      - "5000:5000"
    environment:
      - PG_HOST=postgres
      - PG_USER=flask_rw
      - FLASK_RW_PWD=local
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nw

  nginx:
    profiles:
      - all
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/static:/app/static
    ports:
      - "8080:80"
    depends_on:
      - nifty
    networks:
      - nw

networks:
  nw:

volumes:
  postgres-data:
