version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]
      interval: 1s
      timeout: 20s
      retries: 20
      start_period: 1s
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nw

  redis:
    container_name: redis
    image: redis:7.0.7
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --user healthcheck --pass hclocal ping | grep PONG" ]
      interval: 1s
      timeout: 30s
      retries: 30
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - nw

  redis-cache:
    container_name: redis-cache
    image: redis:7.0.7
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --user healthcheck --pass hclocal ping | grep PONG" ]
      interval: 1s
      timeout: 30s
      retries: 30
    volumes:
      - ./config/redis-cache.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - nw

  trend:
    profiles:
      - worker
      - all
    container_name: trend
    image: acartine/nifty-trend:v1
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - REDIS_HOST=redis
      - TREND_REDIS_PWD=${TREND_REDIS_PWD}
      - TREND_REDIS_USER=${TREND_REDIS_USER}
    depends_on:
      redis:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    networks:
      - nw

  trend-link:
    profiles:
      - worker
      - all
    container_name: trend-link
    image: acartine/nifty-trend-link:v1
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - REDIS_HOST=redis
      - TREND_LINK_REDIS_PWD=${TREND_LINK_REDIS_PWD}
      - TREND_LINK_REDIS_USER=${TREND_LINK_REDIS_USER}
    depends_on:
      redis:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    networks:
      - nw

  nifty:
    profiles:
      - base
      - all
    container_name: nifty
    image: acartine/nifty:v1
    ports:
      - "5000:5000"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_CACHE_HOST=redis-cache
      - NIFTY_PG_PWD=${NIFTY_PG_PWD}
      - NIFTY_PG_USER=${NIFTY_PG_USER}
      - NIFTY_REDIS_PWD=${NIFTY_REDIS_PWD}
      - NIFTY_REDIS_USER=${NIFTY_REDIS_USER}
      - NIFTY_REDIS_CACHE_PWD=${NIFTY_REDIS_CACHE_PWD}
      - NIFTY_REDIS_CACHE_USER=${NIFTY_REDIS_CACHE_USER}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    networks:
      - nw

  nginx:
    profiles:
      - base
      - all
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nifty/service/static:/app/static
    ports:
      - "8080:80"
    depends_on:
      - nifty
    networks:
      - nw

networks:
  nw:

volumes:
  postgres-data:
